import json
import os
import pandas as pd
import numpy as np
from modules.firebase_manager import get_firestore_client, is_firebase_active

DB_FILE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data', 'student_db.json')

def load_student_db():
    """
    Loads all student records. If Firebase is active, pulls from Firestore.
    Otherwise falls back to persistent local JSON.
    """
    if is_firebase_active():
        try:
            firestore_db = get_firestore_client()
            docs = firestore_db.collection("students").stream()
            records = []
            for doc in docs:
                records.append(doc.to_dict())
            return records
        except Exception as e:
            print(f"Firebase fetch failed, falling back to JSON: {e}")
            # If API is disabled or throws error, we disable firebase to avoid failing again
            import modules.firebase_manager as fbm
            fbm.disable_firebase() # Force dynamic fallback mode

    if not os.path.exists(DB_FILE_PATH):
        # Create directory if missing
        os.makedirs(os.path.dirname(DB_FILE_PATH), exist_ok=True)
        with open(DB_FILE_PATH, 'w') as f:
            json.dump([], f)
        return []
        
    try:
        with open(DB_FILE_PATH, 'r') as f:
            return json.load(f)
    except Exception:
        return []

def save_student_db(records):
    """
    Writes the list of student records back to database.
    Saves to Firestore if active, and also maintains a local JSON backup.
    """
    if is_firebase_active():
        try:
            firestore_db = get_firestore_client()
            # Batch write to Firestore
            batch = firestore_db.batch()
            for student in records:
                # Document ID generated by composite unique key
                doc_id = f"{student['RollNo']}_{student.get('Subject', 'General')}_{student.get('CreatedBy', 'admin')}".replace('/', '_').replace('.', '_')
                doc_ref = firestore_db.collection("students").document(doc_id)
                batch.set(doc_ref, student)
            batch.commit()
        except Exception as e:
            print(f"Firebase write failed: {e}")
            import modules.firebase_manager as fbm
            fbm.disable_firebase()

    # Maintain local JSON copy
    os.makedirs(os.path.dirname(DB_FILE_PATH), exist_ok=True)
    with open(DB_FILE_PATH, 'w') as f:
        json.dump(records, f, indent=4)

def clear_db():
    """
    Resets the student database. Clears Firestore collections and JSON.
    """
    if is_firebase_active():
        try:
            firestore_db = get_firestore_client()
            docs = firestore_db.collection("students").stream()
            batch = firestore_db.batch()
            for doc in docs:
                batch.delete(doc.reference)
            batch.commit()
        except Exception as e:
            print(f"Firebase clear failed: {e}")
            
    save_student_db([])

def recompute_average_and_category(student):
    """
    Recomputes the average and performance classification of a student record
    using the formula: Average = 80% * Best + 20% * Least
    """
    mid1 = student.get('Mid1', None)
    mid2 = student.get('Mid2', None)
    
    # Coerce to float or keep as None if not entered yet
    if mid1 == "" or mid1 is None:
        m1_val = None
    else:
        try:
            m1_val = float(mid1)
        except ValueError:
            m1_val = 0.0

    if mid2 == "" or mid2 is None:
        m2_val = None
    else:
        try:
            m2_val = float(mid2)
        except ValueError:
            m2_val = 0.0

    # If neither mid marks are entered, we don't calculate average yet
    if m1_val is None and m2_val is None:
        student['Average'] = ""
        student['Performance_Category'] = "Unassigned"
        return student

    # Impute missing values as 0.0 if only one is present
    m1_clean = m1_val if m1_val is not None else 0.0
    m2_clean = m2_val if m2_val is not None else 0.0

    # Best-Least weighted average calculation (80% best + 20% least)
    best = max(m1_clean, m2_clean)
    least = min(m1_clean, m2_clean)
    avg_score = (0.8 * best) + (0.2 * least)
    
    student['Mid1'] = round(m1_clean, 2)
    student['Mid2'] = round(m2_clean, 2)
    student['Average'] = round(avg_score, 2)
    
    # Categorization based on 80/20 Average scaled for 25 max marks
    if avg_score > 20.0:
        student['Performance_Category'] = 'High Performance'
    elif avg_score >= 12.5:
        student['Performance_Category'] = 'Medium Performance'
    else:
        student['Performance_Category'] = 'Low Performance'
        
    return student

def add_or_update_students(df_new, faculty_username="admin", default_subject="General"):
    """
    Merges student profile records (Name, RollNo, Branch, MobileNumber, Email, Subject) 
    from a DataFrame into the persistent JSON database.
    Matches records by RollNo, Subject, and CreatedBy. If a record already exists, updates details.
    Ensures that a student (RollNo) cannot be registered for the same subject by another faculty member.
    Returns a tuple of (pd.DataFrame, list_of_skipped_duplicates)
    """
    db_records = load_student_db()
    
    # Create lookup map by (RollNo, Subject, CreatedBy) for updates
    db_map = {
        (
            str(r['RollNo']).strip().upper(), 
            str(r.get('Subject', 'General')).strip().upper(), 
            r.get('CreatedBy', 'admin')
        ): r for r in db_records
    }
    
    # Global map to track (RollNo, Subject) mapping to CreatedBy faculty
    global_map = {
        (
            str(r['RollNo']).strip().upper(), 
            str(r.get('Subject', 'General')).strip().upper()
        ): r.get('CreatedBy', 'admin') for r in db_records
    }
    
    skipped_duplicates = []
    
    for _, row in df_new.iterrows():
        roll_no = str(row['RollNo']).strip().upper()
        subject = str(row.get('Subject', default_subject)).strip()
        subject_key = subject.upper()
        
        name = str(row.get('Name', '')).strip()
        branch = str(row.get('Branch', '')).strip().upper()
        mobile = str(row.get('MobileNumber', '')).strip()
        email = str(row.get('Email', '')).strip()
        
        key = (roll_no, subject_key, faculty_username)
        global_key = (roll_no, subject_key)
        
        # Check if student is already registered for this subject by a DIFFERENT faculty member
        if global_key in global_map and global_map[global_key] != faculty_username:
            skipped_duplicates.append((roll_no, subject, global_map[global_key]))
            continue
            
        # Check if student already exists in database for this faculty and subject
        if key in db_map:
            # Update contact details only
            db_map[key]['Name'] = name if name else db_map[key].get('Name', '')
            db_map[key]['Branch'] = branch if branch else db_map[key].get('Branch', '')
            db_map[key]['MobileNumber'] = mobile if mobile else db_map[key].get('MobileNumber', '')
            db_map[key]['Email'] = email if email else db_map[key].get('Email', '')
            
            # If spreadsheet also uploaded mid marks, update them
            if 'Mid1' in row and row['Mid1'] != "":
                db_map[key]['Mid1'] = row['Mid1']
            if 'Mid2' in row and row['Mid2'] != "":
                db_map[key]['Mid2'] = row['Mid2']
                
            # Recompute grades
            db_map[key] = recompute_average_and_category(db_map[key])
        else:
            # Add new student record
            new_student = {
                "RollNo": roll_no,
                "Name": name,
                "Branch": branch,
                "MobileNumber": mobile,
                "Email": email,
                "Subject": subject,
                "Mid1": row.get('Mid1', ""),
                "Mid2": row.get('Mid2', ""),
                "Average": "",
                "Performance_Category": "Unassigned",
                "CreatedBy": faculty_username
            }
            new_student = recompute_average_and_category(new_student)
            db_records.append(new_student)
            db_map[key] = new_student
            # Update the global map to track newly added student in current batch
            global_map[global_key] = faculty_username
            
    # Save back to disk
    save_student_db(db_records)
    
    # Return full database as clean pandas DataFrame and the list of skipped duplicates
    return pd.DataFrame(db_records), skipped_duplicates

def upload_mid_marks_db(df_marks, faculty_username="admin", default_subject="General"):
    """
    Parses a DataFrame containing RollNo, Mid1, and/or Mid2 marks, 
    matches them to persistent student database records by RollNo, Subject, and CreatedBy,
    calculates weighted averages, and saves database.
    Returns (updated_df, success_count, missing_students_list)
    """
    db_records = load_student_db()
    db_map = {
        (
            str(r['RollNo']).strip().upper(), 
            str(r.get('Subject', 'General')).strip().upper(), 
            r.get('CreatedBy', 'admin')
        ): r for r in db_records
    }
    
    success_count = 0
    missing_students = []
    
    for _, row in df_marks.iterrows():
        roll_no = str(row['RollNo']).strip().upper()
        subject = str(row.get('Subject', default_subject)).strip().upper()
        key = (roll_no, subject, faculty_username)
        
        if key in db_map:
            # Update marks if present in uploaded marks file
            if 'Mid1' in row and row['Mid1'] != "":
                db_map[key]['Mid1'] = row['Mid1']
            if 'Mid2' in row and row['Mid2'] != "":
                db_map[key]['Mid2'] = row['Mid2']
                
            # Re-evaluate student performance metrics
            db_map[key] = recompute_average_and_category(db_map[key])
            success_count += 1
        else:
            missing_students.append(f"{roll_no} ({subject})")
            
    # Save database updates
    save_student_db(db_records)
    
    return pd.DataFrame(db_records), success_count, missing_students

def rename_subject(faculty_username, old_subject, new_subject):
    """
    Renames a subject for all students managed by a specific faculty member.
    """
    db_records = load_student_db()
    old_sub_clean = old_subject.strip().upper()
    new_sub_clean = new_subject.strip().upper()
    
    updated_count = 0
    for s in db_records:
        if s.get('CreatedBy') == faculty_username and str(s.get('Subject', 'General')).strip().upper() == old_sub_clean:
            s['Subject'] = new_subject.strip()
            updated_count += 1
            
    if updated_count > 0:
        save_student_db(db_records)
    return updated_count
